[package]
name = "house-price-predictor"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
csv = "1.2"
anyhow = "1.0"
polars = { version = "0.37.0", features = ["csv", "lazy"] }
rand = "0.8.5"
